# Generated by Django 5.1.3 on 2025-01-04 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_element', models.CharField(max_length=50)),
                ('credit', models.IntegerField()),
                ('penderation', models.DecimalField(decimal_places=3, default=1, max_digits=4)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('cne', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('prenom', models.CharField(max_length=30)),
                ('nom', models.CharField(max_length=30)),
                ('cin', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=20)),
                ('date_naissance', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=15)),
                ('adresse', models.CharField(max_length=150)),
                ('nationalite', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id_professeur', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('prenom', models.CharField(max_length=30)),
                ('nom', models.CharField(max_length=30)),
                ('cin', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=20)),
                ('date_naissance', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=15)),
                ('adresse', models.CharField(max_length=150)),
                ('nationalite', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_ordinaire', models.DecimalField(db_column='OrdinaryMark', decimal_places=3, max_digits=5)),
                ('note_rattrapage', models.DecimalField(blank=True, db_column='CatchUpMark', decimal_places=3, max_digits=5, null=True)),
                ('annee', models.IntegerField()),
                ('element', models.ForeignKey(db_column='element', on_delete=django.db.models.deletion.CASCADE, to='Grades.element')),
                ('etudiant', models.ForeignKey(db_column='etudiant', on_delete=django.db.models.deletion.CASCADE, to='Grades.etudiant')),
            ],
        ),
        migrations.AddField(
            model_name='element',
            name='professeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grades.professeur'),
        ),
    ]
