# Generated by Django 5.1.3 on 2025-01-09 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('cne', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('cin', models.CharField(max_length=8, unique=True)),
                ('nom_etudiant', models.CharField(max_length=20)),
                ('prenom_etudiant', models.CharField(max_length=20)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=20)),
                ('adress', models.CharField(max_length=50)),
                ('genre', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], max_length=1)),
                ('telephone', models.CharField(max_length=10)),
                ('email_acadymic', models.EmailField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id_professeur', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('cin', models.CharField(max_length=7, unique=True)),
                ('nom_professeur', models.CharField(default='', max_length=20)),
                ('prenom_professeur', models.CharField(default='', max_length=20)),
                ('email_professeur', models.EmailField(default='', max_length=50, unique=True)),
                ('num_telephone', models.CharField(max_length=10)),
                ('fonction', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_element', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200, unique=True)),
                ('volums_horaire', models.IntegerField()),
                ('type_element', models.CharField(max_length=20)),
                ('coiefficient', models.FloatField(default=1)),
                ('note_credit', models.IntegerField()),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grades.professeur')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_ordinaire', models.DecimalField(decimal_places=2, max_digits=5)),
                ('note_rattrapage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('annee_academique', models.CharField(max_length=12)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grades.element')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grades.etudiant')),
            ],
            options={
                'unique_together': {('element', 'etudiant', 'annee_academique')},
            },
        ),
    ]
