# Generated by Django 5.1.3 on 2024-12-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0002_element_etudiant_evaluation_delete_professeur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='genre',
            field=models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], max_length=1),
        ),
    ]
