# Generated by Django 5.1.3 on 2024-12-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0003_alter_etudiant_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin', models.CharField(max_length=7)),
                ('nom_professeur', models.CharField(max_length=20)),
                ('prenom_professeur', models.CharField(max_length=20)),
                ('email_professeur', models.CharField(max_length=30)),
                ('num_telephone', models.CharField(max_length=10)),
                ('fonction', models.CharField(max_length=10)),
            ],
        ),
    ]
