# Generated by Django 5.1.3 on 2025-01-20 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0003_remove_element_professeur_alter_evaluation_element_and_more'),
        ('insc_reeinsc_admin', '0006_remove_element_professeur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignement',
            fields=[
                ('id_enseignement', models.CharField(primary_key=True, serialize=False)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseignements', to='insc_reeinsc_admin.element')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseignements', to='insc_reeinsc_admin.professeur')),
            ],
        ),
    ]
