# Generated by Django 5.1.3 on 2024-12-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0004_professeur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('professeurs', models.ManyToManyField(related_name='groupes', to='Grades.professeur')),
            ],
        ),
    ]
