# Generated by Django 5.1.3 on 2025-01-22 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0004_enseignement'),
        ('insc_reeinsc_admin', '0007_remove_professeur_id_prof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignement',
            name='professeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseignements', to='insc_reeinsc_admin.professeur', to_field='email_prof'),
        ),
    ]
