# Generated by Django 5.1.3 on 2025-03-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0005_alter_enseignement_professeur'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enseignement',
            options={'verbose_name': 'Enseignement', 'verbose_name_plural': 'Enseignements'},
        ),
        migrations.AlterField(
            model_name='enseignement',
            name='id_enseignement',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
