# Generated by Django 5.1.3 on 2025-03-28 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0006_alter_enseignement_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enseignement',
            options={},
        ),
    ]
