# Generated by Django 5.1.3 on 2024-12-30 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0009_remove_evaluation_id_element_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cne', models.CharField(max_length=10, unique=True)),
                ('cin', models.CharField(max_length=8, unique=True)),
                ('nom_etudiant', models.CharField(max_length=20)),
                ('prenom_etudiant', models.CharField(max_length=20)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=20)),
                ('adress', models.CharField(max_length=50)),
                ('genre', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], max_length=1)),
                ('telephone', models.CharField(max_length=10)),
                ('email_acadymic', models.EmailField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='professeur',
            name='cin',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='email_professeur',
            field=models.EmailField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, unique=True)),
                ('volums_horaire', models.IntegerField()),
                ('type_element', models.CharField(max_length=20)),
                ('coiefficient', models.FloatField(default=1)),
                ('note_credit', models.IntegerField()),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grades.professeur')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_ordinaire', models.FloatField()),
                ('note_rattrapage', models.FloatField()),
                ('annee', models.IntegerField()),
                ('id_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grades.element')),
                ('id_etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grades.etudiant')),
            ],
            options={
                'unique_together': {('id_element', 'id_etudiant', 'annee')},
            },
        ),
    ]
