# Generated by Django 5.1.3 on 2025-01-05 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0014_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
