# Generated by Django 5.1.3 on 2025-01-06 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0015_delete_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professeur',
            name='user',
        ),
    ]
