# Generated by Django 5.1.3 on 2025-01-08 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0017_alter_evaluation_note_ordinaire_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='element',
            table='Grades_element',
        ),
        migrations.AlterModelTable(
            name='etudiant',
            table='Grades_etudiant',
        ),
        migrations.AlterModelTable(
            name='evaluation',
            table='Grades_evaluation',
        ),
        migrations.AlterModelTable(
            name='professeur',
            table='Grades_professeur',
        ),
    ]
