# Generated by Django 5.1.3 on 2025-01-08 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0018_alter_element_table_alter_etudiant_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='element',
            table=None,
        ),
        migrations.AlterModelTable(
            name='etudiant',
            table=None,
        ),
        migrations.AlterModelTable(
            name='evaluation',
            table=None,
        ),
        migrations.AlterModelTable(
            name='professeur',
            table=None,
        ),
    ]
