# Generated by Django 5.1.3 on 2025-01-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id_dept', models.AutoField(primary_key=True, serialize=False)),
                ('nom_departement', models.CharField(max_length=255, unique=True, verbose_name='Nom du département')),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'ordering': ['nom_departement'],
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('image_std', models.ImageField(upload_to='uploads/images')),
                ('cin_std', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name="CIN d'etudiant")),
                ('cne_std', models.CharField(max_length=20, verbose_name="CNE d'etudiant")),
                ('nom_std', models.CharField(max_length=50, verbose_name="Nom d'etudiant")),
                ('prenom_std', models.CharField(blank=True, max_length=50, verbose_name="Prenom d'etudiant")),
                ('date_naiss', models.DateField(blank=True, verbose_name='Date de naissance')),
                ('nationalite_std', models.CharField(blank=True, max_length=50, verbose_name="Nationalite d'etudiant")),
                ('pays_std', models.CharField(blank=True, max_length=50, verbose_name="Pays d'etudiant")),
                ('region', models.CharField(blank=True, max_length=50, verbose_name='Region')),
                ('addresse_postal', models.CharField(blank=True, max_length=100, verbose_name='Addresse postal')),
                ('code_postal', models.CharField(blank=True, max_length=50, verbose_name='Code postal')),
                ('ville_std', models.CharField(blank=True, max_length=50, verbose_name="Ville d'etudiant")),
                ('adrs_std', models.CharField(blank=True, max_length=100, verbose_name="Addresse d'etudiant")),
                ('annee_etude', models.CharField(choices=[('1', 'Première Année'), ('2', 'Deuxième Année'), ('3', 'Troisième Année'), ('4', 'Quatrième Année'), ('5', 'Cinquième Année')], default='1', max_length=50)),
                ('serie_bac', models.CharField(blank=True, max_length=50, verbose_name='Série du baccalauréat')),
                ('annee_obtention_bac', models.CharField(blank=True, max_length=50, verbose_name="Année d'obtention du baccalauréat")),
                ('mention_bac', models.CharField(blank=True, max_length=50, verbose_name='Mention au baccalauréat')),
                ('etablissement_origine', models.CharField(blank=True, max_length=50, verbose_name="Établissement d'origine")),
                ('num_tele_std', models.CharField(max_length=15, unique=True, verbose_name='Numéro de téléphone')),
                ('email_std', models.EmailField(max_length=100, unique=True, verbose_name="Email Personnel d'etudiant")),
                ('password_std', models.CharField(max_length=100, unique=True, verbose_name="Password Personnel d'etudiant")),
            ],
            options={
                'verbose_name': 'Etudiant',
                'verbose_name_plural': 'Etudiants',
                'ordering': ['nom_std'],
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('nom_filiere', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Nom du filiere')),
                ('type_diplome', models.CharField(max_length=20, verbose_name='Type de diplome du filiere')),
                ('semestres', models.CharField(max_length=20, verbose_name='Semestres du filiere')),
            ],
            options={
                'verbose_name': 'Filiere',
                'verbose_name_plural': 'Filieres',
                'ordering': ['nom_filiere'],
            },
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('image_prof', models.ImageField(upload_to='uploads/images')),
                ('cin_prof', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='CIN du professeur')),
                ('nom_prof', models.CharField(max_length=50, verbose_name='Nom du professeur')),
                ('prenom_prof', models.CharField(blank=True, max_length=50, verbose_name='Prenom du professeur')),
                ('adrs_prof', models.CharField(blank=True, max_length=100, verbose_name='Addresse du professeur')),
                ('email_prof', models.EmailField(max_length=100, unique=True, verbose_name='Email du professeur')),
                ('num_tele_prof', models.CharField(max_length=15, unique=True, verbose_name='Numéro de téléphone')),
                ('degre_prof', models.CharField(blank=True, max_length=100, null=True)),
                ('fonction_prof', models.CharField(default='Enseignant', max_length=50, verbose_name='Fonction du professeur')),
            ],
            options={
                'verbose_name': 'Professeur',
                'verbose_name_plural': 'Professeurs',
                'ordering': ['nom_prof'],
            },
        ),
    ]
