# Generated by Django 5.1.3 on 2025-01-19 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insc_reeinsc_admin', '0001_initial'),
        ('pfe_absence_sfe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='groupe_std',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupe_etudiant', to='pfe_absence_sfe.groupepfe', verbose_name="Le Groupe d'etudiant"),
        ),
        migrations.AddField(
            model_name='filiere',
            name='dept_filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_filiere', to='insc_reeinsc_admin.departement', verbose_name='Departement du filiere'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='filiere_std',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filiere_etudiant', to='insc_reeinsc_admin.filiere', verbose_name="La Filiere d'etudiant"),
        ),
        migrations.AddField(
            model_name='filiere',
            name='coord_filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordonateur_filiere', to='insc_reeinsc_admin.professeur', verbose_name='Coordonateur du filiere'),
        ),
        migrations.AddField(
            model_name='filiere',
            name='equipe_pydagogique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipe_pydagogique_filiere', to='insc_reeinsc_admin.professeur', verbose_name='Equipe pydagogique du filiere'),
        ),
        migrations.AddField(
            model_name='departement',
            name='coordonateur_dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordonateur_departements', to='insc_reeinsc_admin.professeur', verbose_name='Coordonateur du département'),
        ),
    ]
