# Generated by Django 5.1.3 on 2025-01-19 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insc_reeinsc_admin', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('nom_module', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Nom du module')),
                ('charge_horaire', models.CharField(blank=True, max_length=10, verbose_name="Charge d'horaire du module")),
                ('coef_module', models.CharField(blank=True, max_length=10, verbose_name='Coefecient du module')),
                ('nombre_element', models.PositiveIntegerField(default=0, verbose_name="Nombre d'éléments")),
                ('coord_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordonateur_module', to='insc_reeinsc_admin.professeur', verbose_name='Coordonateur du module')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'ordering': ['nom_module'],
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('nom_element', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name="Nom d'element")),
                ('heure_tp', models.CharField(blank=True, max_length=10, verbose_name="Heure tp d'element")),
                ('heure_td', models.CharField(blank=True, max_length=10, verbose_name="Heure td d'element")),
                ('heure_cours', models.CharField(blank=True, max_length=10, verbose_name="Heure cours d'element")),
                ('penderation_element', models.CharField(blank=True, max_length=10, verbose_name="Penderation d'element")),
                ('module_elm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insc_reeinsc_admin.module', verbose_name='Module')),
            ],
            options={
                'verbose_name': 'Element',
                'verbose_name_plural': 'Elements',
                'ordering': ['nom_element'],
            },
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id_semestre', models.AutoField(primary_key=True, serialize=False, verbose_name='ID du semestre')),
                ('nom_semestre', models.CharField(max_length=10, verbose_name='Nom du semestre')),
                ('nombre_modules', models.PositiveIntegerField(default=0, verbose_name='Nombre de modules')),
                ('filiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semestres_filiere', to='insc_reeinsc_admin.filiere', verbose_name='Filière du semestre')),
            ],
            options={
                'verbose_name': 'Semestre',
                'verbose_name_plural': 'Semestres',
                'ordering': ['nom_semestre'],
            },
        ),
        migrations.AddField(
            model_name='module',
            name='semestre_mod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semestre_modules', to='insc_reeinsc_admin.semestre', verbose_name='Semestre de modeles'),
        ),
    ]
