# Generated by Django 5.1.3 on 2025-01-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insc_reeinsc_admin', '0004_element_professeur_professeur_id_prof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professeur',
            name='id_prof',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
