# Generated by Django 5.1.3 on 2025-01-20 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insc_reeinsc_admin', '0005_alter_professeur_id_prof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='professeur',
        ),
    ]
