# Generated by Django 5.1.3 on 2025-03-28 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insc_reeinsc_admin', '0007_remove_professeur_id_prof'),
    ]

    operations = [
        migrations.AddField(
            model_name='professeur',
            name='departement_prof',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professeurs', to='insc_reeinsc_admin.departement', verbose_name='Département professeur'),
        ),
    ]
