# Generated by Django 5.1.3 on 2025-03-28 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insc_reeinsc_admin', '0008_professeur_departement_prof'),
    ]

    operations = [
    ]
