# Generated by Django 5.1.3 on 2025-01-19 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insc_reeinsc_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupePfe',
            fields=[
                ('id_groupe', models.AutoField(primary_key=True, serialize=False)),
                ('nom_groupe', models.CharField(max_length=50)),
                ('type_groupe', models.CharField(choices=[('MONOME', 'Monôme'), ('BINOME', 'Binôme')], default='MONOME', max_length=6)),
                ('date_creation', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id_demande', models.AutoField(primary_key=True, serialize=False)),
                ('date_demande', models.DateField(auto_now_add=True)),
                ('etat_demande', models.CharField(choices=[('Accepter', 'accepter'), ('Refuser', 'refuser'), ('en_attente', 'en attente')], default='en_attente', max_length=10)),
                ('id_demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demande_etudiant_demendeur', to='insc_reeinsc_admin.etudiant')),
                ('id_recepteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damande_etudiant_recepteur', to='insc_reeinsc_admin.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Pfe',
            fields=[
                ('id_pfe', models.AutoField(primary_key=True, serialize=False)),
                ('sujet', models.CharField(max_length=100)),
                ('encadrant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pfe_professeur', to='insc_reeinsc_admin.professeur')),
                ('groupe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='groupes_pfe', to='pfe_absence_sfe.groupepfe')),
            ],
        ),
    ]
